
AWSTemplateFormatVersion: "2010-09-09"
Description: "Smart Photo Album"
Parameters:

    S3Bucket2Name:
        Type: "String"
        Default: "b2photoss"

    S3BucketName:
        Type: "String"
        Default: "b1photoalbum"

    LambdaFunction2Name:
        Type: "String"
        Default: "index-photos"

    LambdaFunctionName:
        Type: "String"
        Default: "search-photos"

    GitHubOwner:
        Type: String
        Default: phananh1096
        AllowedPattern: '[A-Za-z0-9-]+'

    GitHubRepo:
        Type: String
        Default: A2-Frontend
        AllowedPattern: '[A-Za-z0-9-]+'

    GitHubBranch:
        Type: String
        Default: main
        AllowedPattern: '[A-Za-z0-9-]+'

    GitHubOAuthToken:
        Type: String
        Default: '2b811ae58dcf52fa7cd184ba29913137916248ba'
        NoEcho: true
        MinLength: 40
        MaxLength: 40
        AllowedPattern: '[a-z0-9]*'
        
Resources:
    LambdaFunction:
        Type: "AWS::Lambda::Function"
        Properties:
            Description: ""
            FunctionName: !Ref LambdaFunctionName
            Handler: "lambda_function.lambda_handler"
            Architectures: 
              - "x86_64"
            Code: 
                S3Bucket: "eashan-kaushik-public"
                S3Key: "index-photos.zip"
            MemorySize: 128
            Role: !GetAtt IAMRole.Arn
            Runtime: "python3.7"
            Timeout: 123
            TracingConfig: 
                Mode: "PassThrough"
            Layers: 
              - !Sub "arn:aws:lambda:us-east-1:770693421928:layer:Klayers-python38-elasticsearch:38"
              -"arn:aws:lambda:us-east-1:770693421928:layer:Klayers-python38-aws-requests-auth:20"
            EphemeralStorage: 
                Size: 512

    LambdaFunction2:
        Type: "AWS::Lambda::Function"
        Properties:
            Description: ""
            FunctionName: !Ref LambdaFunction2Name
            Handler: "lambda_function.lambda_handler"
            Architectures: 
              - "x86_64"
            Code: 
                S3Bucket: "eashan-kaushik-public"
                S3Key: "search-photos.zip"
            MemorySize: 128
            Role: !GetAtt IAMRole2.Arn
            Runtime: "python3.7"
            Timeout: 123
            TracingConfig: 
                Mode: "PassThrough"
            Layers: 
              - !Sub "arn:aws:lambda:us-east-1:770693421928:layer:Klayers-python38-elasticsearch:38"
              -"arn:aws:lambda:us-east-1:770693421928:layer:Klayers-python38-aws-requests-auth:20"
            EphemeralStorage: 
                Size: 512

    S3Bucket:
        Type: "AWS::S3::Bucket"
        Properties:
            BucketName: !Ref S3BucketName
            WebsiteConfiguration: 
                IndexDocument: "index.html"

    S3Bucket2:
        Type: "AWS::S3::Bucket"
        Properties:
            BucketName: !Ref S3Bucket2Name
            NotificationConfiguration: 
                LambdaConfigurations: 
                  - 
                    Event: "s3:ObjectCreated:Put"
                    Function: !GetAtt LambdaFunction2.Arn


    ApiGatewayRestApi:
        Type: "AWS::ApiGateway::RestApi"
        Properties:
            Name: "AI Photo Search"
            Description: "AI Photo Search application, built during the Cloud and Big Data course at Columbia University."
            ApiKeySourceType: "HEADER"
            BinaryMediaTypes: 
              - "image/*"
              - "image/jpeg"
              - "image/jpg"
              - "image/png"

            EndpointConfiguration: 
                Types: 
                  - "REGIONAL"

    CodeBuildProject:
        Type: "AWS::CodeBuild::Project"
        Properties:
            Name: "LambdaPhotoAlbumCodeBuild"
            Source: 
                InsecureSsl: false
                Type: "CODEPIPELINE"
            Artifacts: 
                EncryptionDisabled: false
                Name: "LambdaPhotoAlbumCodeBuild"
                Packaging: "NONE"
                Type: "CODEPIPELINE"
            Cache: 
                Type: "NO_CACHE"
            Environment: 
                ComputeType: "BUILD_GENERAL1_SMALL"
                Image: "aws/codebuild/standard:6.0"
                ImagePullCredentialsType: "CODEBUILD"
                PrivilegedMode: false
                Type: "LINUX_CONTAINER"
            ServiceRole: !Sub "arn:aws:iam::${AWS::AccountId}:role/service-role/codebuild-LambdaPhotoAlbumCodeBuild-service-role"
            TimeoutInMinutes: 60
            QueuedTimeoutInMinutes: 480
            EncryptionKey: !Sub "arn:aws:kms:${AWS::Region}:${AWS::AccountId}:alias/aws/s3"
            BadgeEnabled: false
            LogsConfig: 
                CloudWatchLogs: 
                    Status: "ENABLED"
                S3Logs: 
                    Status: "DISABLED"
                    EncryptionDisabled: false
            Visibility: "PRIVATE"

    CodePipelinePipeline:
        Type: "AWS::CodePipeline::Pipeline"
        Properties:
            Name: "FrontendPhotoAlbumPipeline"
            RoleArn: !GetAtt IAMRole4.Arn
            ArtifactStore: 
                Location: !Sub "codepipeline-${AWS::Region}-511494083853"
                Type: "S3"
            Stages: 
              - Name: "Source"
                Actions: 
                  - Name: "Source"
                    ActionTypeId: 
                        Category: "Source"
                        Owner: "AWS"
                        Provider: "CodeCommit"
                        Version: "1"
                    Configuration: 
                        {
                        'Owner': !Ref GitHubOwner,
                        'Repo': !Ref GitHubRepo,
                        'Branch': !Ref GitHubBranch,
                        'OAuthToken': !Ref GitHubOAuthToken,
                        }
                    OutputArtifacts: 
                      - Name: "SourceArtifact"
                    Region: !Ref AWS::Region
                    Namespace: "SourceVariables"
                    RunOrder: 1
              - Name: "Deploy"
                Actions: 
                  - Name: "Deploy"
                    ActionTypeId: 
                        Category: "Deploy"
                        Owner: "AWS"
                        Provider: "S3"
                        Version: "1"
                    Configuration: 
                        BucketName: !Ref S3Bucket
                        Extract: "true"
                    InputArtifacts: 
                      - Name: "SourceArtifact"
                    Region: !Ref AWS::Region
                    Namespace: "DeployVariables"
                    RunOrder: 1

    CodePipelinePipeline2:
        Type: "AWS::CodePipeline::Pipeline"
        Properties:
            Name: "LambdaPhotoAlbumPipeline"
            RoleArn: !GetAtt IAMRole5.Arn
            ArtifactStore: 
                Location: !Sub "codepipeline-${AWS::Region}-511494083853"
                Type: "S3"
            Stages: 
              - Name: "Source"
                Actions: 
                  - Name: "Source"
                    ActionTypeId: 
                        Category: "Source"
                        Owner: "AWS"
                        Provider: "CodeCommit"
                        Version: "1"
                    Configuration: 
                        {
                        'Owner': !Ref GitHubOwner,
                        'Repo': !Ref GitHubRepo,
                        'Branch': !Ref GitHubBranch,
                        'OAuthToken': !Ref GitHubOAuthToken,
                        }
                    OutputArtifacts: 
                      - Name: "SourceArtifact"
                    Region: !Ref AWS::Region
                    Namespace: "SourceVariables"
                    RunOrder: 1
              - Name: "Build"
                Actions: 
                  - Name: "Build"
                    ActionTypeId: 
                        Category: "Build"
                        Owner: "AWS"
                        Provider: "CodeBuild"
                        Version: "1"
                    Configuration: 
                        ProjectName: !Ref CodeBuildProject
                    InputArtifacts: 
                      - Name: "SourceArtifact"
                    OutputArtifacts: 
                      - Name: "BuildArtifact"
                    Region: !Ref AWS::Region
                    Namespace: "BuildVariables"
                    RunOrder: 1
              - Name: "Deploy"
                Actions: 
                  - Name: "Deploy"
                    ActionTypeId: 
                        Category: "Deploy"
                        Owner: "AWS"
                        Provider: "CloudFormation"
                        Version: "1"
                    Configuration: 
                        ActionMode: "CHANGE_SET_REPLACE"
                        Capabilities: "CAPABILITY_IAM"
                        ChangeSetName: "LambdaCICD"
                        RoleArn: !GetAtt IAMRole7.Arn
                        StackName: "LambdaCICD"
                        TemplatePath: "BuildArtifact::outSamTemplate.yaml"
                    InputArtifacts: 
                      - Name: "BuildArtifact"
                    Region: !Ref AWS::Region
                    Namespace: "DeployVariables"
                    RunOrder: 1
              - Name: "ApproveChangeSet"
                Actions: 
                  - Name: "ManualApprovel"
                    ActionTypeId: 
                        Category: "Approval"
                        Owner: "AWS"
                        Provider: "Manual"
                        Version: "1"
                    Configuration: {}
                    Region: !Ref AWS::Region
                    RunOrder: 1
              - Name: "ExecuteChangeSet"
                Actions: 
                  - Name: "Execute"
                    ActionTypeId: 
                        Category: "Deploy"
                        Owner: "AWS"
                        Provider: "CloudFormation"
                        Version: "1"
                    Configuration: 
                        ActionMode: "CHANGE_SET_EXECUTE"
                        ChangeSetName: "LambdaCICD"
                        StackName: "LambdaCICD"
                    Region: !Ref AWS::Region
                    RunOrder: 1


    IAMRole:
        Type: "AWS::IAM::Role"
        Properties:
            Path: "/service-role/"
            RoleName: "index-photos-role-g3cqa5kr"
            AssumeRolePolicyDocument: "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Principal\":{\"Service\":\"lambda.amazonaws.com\"},\"Action\":\"sts:AssumeRole\"}]}"
            MaxSessionDuration: 3600
            ManagedPolicyArns: 
              - !Sub "arn:aws:iam::528978711933:policy/service-role/AWSLambdaBasicExecutionRole-e6a50dc6-3f7d-4cbf-a0fb-063f8198223a"
              - "arn:aws:iam::aws:policy/AmazonRekognitionFullAccess"
              - "arn:aws:iam::aws:policy/AmazonS3FullAccess"
              - "arn:aws:iam::aws:policy/AdministratorAccess"

    IAMRole2:
        Type: "AWS::IAM::Role"
        Properties:
            Path: "/service-role/"
            RoleName: "search-photos-role-xmn1paka"
            AssumeRolePolicyDocument: "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Principal\":{\"Service\":\"lambda.amazonaws.com\"},\"Action\":\"sts:AssumeRole\"}]}"
            MaxSessionDuration: 3600
            ManagedPolicyArns: 
              - !Sub "arn:aws:iam::528978711933:policy/service-role/AWSLambdaBasicExecutionRole-f0df82b8-b151-48a8-b022-96dd9fe51f44"
              - "arn:aws:iam::aws:policy/AdministratorAccess"
              - "arn:aws:iam::aws:policy/AmazonLexFullAccess"

    IAMRole3:
        Type: "AWS::IAM::Role"
        Properties:
            Path: "/"
            RoleName: "s3-photos"
            AssumeRolePolicyDocument: "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Sid\":\"\",\"Effect\":\"Allow\",\"Principal\":{\"Service\":\"apigateway.amazonaws.com\"},\"Action\":\"sts:AssumeRole\"}]}"
            MaxSessionDuration: 3600
            ManagedPolicyArns: 
              - !Sub "arn:aws:iam::aws:policy/AmazonS3FullAccess"
              
            Description: "Allows API Gateway to push images to S3"

    IAMRole4:
        Type: "AWS::IAM::Role"
        Properties:
            Path: "/service-role/"
            RoleName: !Sub "AWSCodePipelineServiceRole-${AWS::Region}-FrontendPhotoAlbumPipeline"
            AssumeRolePolicyDocument: "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Principal\":{\"Service\":\"codepipeline.amazonaws.com\"},\"Action\":\"sts:AssumeRole\"}]}"
            MaxSessionDuration: 3600
            ManagedPolicyArns: 
              - !Sub "arn:aws:iam::${AWS::AccountId}:policy/service-role/AWSCodePipelineServiceRole-${AWS::Region}-FrontendPhotoAlbumPipeline"

    IAMRole5:
        Type: "AWS::IAM::Role"
        Properties:
            Path: "/service-role/"
            RoleName: !Sub "AWSCodePipelineServiceRole-${AWS::Region}-LambdaPhotoAlbumPipeline"
            AssumeRolePolicyDocument: "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Principal\":{\"Service\":\"codepipeline.amazonaws.com\"},\"Action\":\"sts:AssumeRole\"}]}"
            MaxSessionDuration: 3600
            ManagedPolicyArns: 
              - !Sub "arn:aws:iam::${AWS::AccountId}:policy/service-role/AWSCodePipelineServiceRole-${AWS::Region}-LambdaPhotoAlbumPipeline"

    IAMRole6:
        Type: "AWS::IAM::Role"
        Properties:
            Path: "/service-role/"
            RoleName: !Sub "codebuild-${CodeBuildProject}-service-role"
            AssumeRolePolicyDocument: "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Principal\":{\"Service\":\"codebuild.amazonaws.com\"},\"Action\":\"sts:AssumeRole\"}]}"
            MaxSessionDuration: 3600
            ManagedPolicyArns: 
              - !Sub "arn:aws:iam::${AWS::AccountId}:policy/service-role/CodeBuildBasePolicy-${CodeBuildProject}-${AWS::Region}"
              - "arn:aws:iam::aws:policy/AmazonS3FullAccess"

    IAMRole7:
        Type: "AWS::IAM::Role"
        Properties:
            Path: "/"
            RoleName: "CloudFormationServiceRole"
            AssumeRolePolicyDocument: "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Sid\":\"\",\"Effect\":\"Allow\",\"Principal\":{\"Service\":\"cloudformation.amazonaws.com\"},\"Action\":\"sts:AssumeRole\"}]}"
            MaxSessionDuration: 3600
            ManagedPolicyArns: 
              - "arn:aws:iam::aws:policy/IAMFullAccess"
              - "arn:aws:iam::aws:policy/AWSLambdaExecute"
              - "arn:aws:iam::aws:policy/AmazonS3FullAccess"
              - "arn:aws:iam::aws:policy/AWSCloudFormationFullAccess"
              - "arn:aws:iam::aws:policy/AWSLambda_FullAccess"
            Description: "Allows CloudFormation to create and manage AWS stacks and resources on your behalf."

    